runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets
  http_headers:
   Access-Control-Allow-Origin: "https://punchsystem-272703.firebaseapp.com/"

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto